apiVersion: v1
kind: Service
metadata:
  labels:
    app: udagram-rev-proxy
  name: udagram-rev-proxy-svc
spec:
  ports:
    - name: '8080'
      port: 8080
      targetPort: 8080
  selector:
    app: udagram-rev-proxy
