apiVersion: v1
kind: Service
metadata:
  labels:
    app: udagram-rev-proxy
  name: udagram-rev-proxy-svc
spec:
  ports:
    - name: '80'
      port: 80
      targetPort: 80
  type: LoadBalancer
  selector:
    app: udagram-rev-proxy
